import {
  Account,
  Contact,
  Opportunity,
  Activity,
  Lead,
  Competitor,
  Contract,
  Proposal,
} from '@/types'

export const mockAccounts: Account[] = [
  {
    id: '1',
    name: 'Stark Industries',
    logo: 'https://img.usecurling.com/i?q=stark&shape=fill&color=azure',
    segment: 'Defesa',
    tier: 'A',
    status: 'Ativo',
    lastInteractionAt: '2023-10-01',
    whiteSpace: 'Falta oferecer soluções cloud.',
  },
  {
    id: '2',
    name: 'Wayne Enterprises',
    logo: 'https://img.usecurling.com/i?q=wayne&shape=fill&color=black',
    segment: 'Tecnologia',
    tier: 'A',
    status: 'Ativo',
    lastInteractionAt: '2023-10-15',
    whiteSpace: 'Expandir cibersegurança.',
  },
  {
    id: '3',
    name: 'Globex Corp',
    logo: 'https://img.usecurling.com/i?q=globex&shape=fill&color=blue',
    segment: 'Manufatura',
    tier: 'B',
    status: 'Inativo',
    lastInteractionAt: '2023-08-10',
    whiteSpace: '',
  },
  {
    id: '4',
    name: 'Initech',
    logo: 'https://img.usecurling.com/i?q=initech&shape=fill&color=gray',
    segment: 'Software',
    tier: 'C',
    status: 'Ativo',
    lastInteractionAt: '2023-10-20',
    whiteSpace: 'Cross-sell de licenças.',
  },
]

export const mockContacts: Contact[] = [
  {
    id: '1',
    accountId: '1',
    name: 'Tony Stark',
    role: 'CEO',
    email: 'tony@stark.com',
    phone: '11999999999',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=1',
    influence: 'Decision Maker',
  },
  {
    id: '2',
    accountId: '1',
    name: 'Pepper Potts',
    role: 'COO',
    email: 'pepper@stark.com',
    phone: '11999999998',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=2',
    influence: 'Champion',
  },
  {
    id: '3',
    accountId: '2',
    name: 'Bruce Wayne',
    role: 'CEO',
    email: 'bruce@wayne.com',
    phone: '11999999997',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=3',
    influence: 'Decision Maker',
  },
]

export const mockOpps: Opportunity[] = [
  {
    id: '1',
    accountId: '1',
    title: 'Migração ERP Global',
    value: 2500000,
    stage: 'Proposta',
    temperature: 'Quente',
    nextStep: 'Aprovação do Board',
    nextStepDate: '2023-11-05',
    isOverdue: false,
    meddic: {
      metrics: 'Reduzir custos em 20%',
      economicBuyer: 'Tony Stark',
      decisionCriteria: 'ROI em 12 meses',
      decisionProcess: 'Aprovação CEO',
      identifyPain: 'Sistemas legados lentos',
      champion: 'Pepper Potts',
    },
  },
  {
    id: '2',
    accountId: '2',
    title: 'Auditoria de Segurança',
    value: 500000,
    stage: 'Qualificação',
    temperature: 'Morna',
    nextStep: 'Demo técnica',
    nextStepDate: '2023-10-25',
    isOverdue: true,
    meddic: {
      metrics: '',
      economicBuyer: 'Bruce Wayne',
      decisionCriteria: '',
      decisionProcess: '',
      identifyPain: 'Vazamento recente',
      champion: '',
    },
  },
  {
    id: '3',
    accountId: '4',
    title: 'Licenças Office 365',
    value: 120000,
    stage: 'Negociação',
    temperature: 'Fria',
    nextStep: 'Assinar contrato',
    nextStepDate: '2023-11-10',
    isOverdue: false,
    meddic: {
      metrics: 'N/A',
      economicBuyer: 'Bill Lumbergh',
      decisionCriteria: 'Preço',
      decisionProcess: 'Compras',
      identifyPain: 'Falta de colaboração',
      champion: 'Milton',
    },
  },
]

export const mockActivities: Activity[] = [
  {
    id: '1',
    relatedTo: 'Opportunity',
    relatedId: '1',
    type: 'Meeting',
    date: '2023-10-20',
    status: 'Concluída',
    summary: 'Apresentação da proposta',
    outcome: 'Positivo',
  },
  {
    id: '2',
    relatedTo: 'Opportunity',
    relatedId: '2',
    type: 'Call',
    date: '2023-10-15',
    status: 'Pendente',
    summary: 'Follow-up demo técnica',
    isOverdue: true,
  },
  {
    id: '3',
    relatedTo: 'Account',
    relatedId: '3',
    type: 'Email',
    date: '2023-08-10',
    status: 'Concluída',
    summary: 'Email de reengajamento',
    outcome: 'Neutro',
  },
]

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Clark Kent',
    company: 'Daily Planet',
    status: 'Novo',
    source: 'Webinar',
    createdAt: '2023-10-22',
  },
  {
    id: '2',
    name: 'Lex Luthor',
    company: 'LexCorp',
    status: 'Qualificado',
    source: 'Indicação',
    createdAt: '2023-10-18',
  },
]

export const mockCompetitors: Competitor[] = [
  {
    id: '1',
    name: 'TechSolutions SA',
    strength: 'Preço agressivo',
    weakness: 'Suporte ruim',
    winRate: '65%',
  },
  {
    id: '2',
    name: 'Global Systems',
    strength: 'Presença global',
    weakness: 'Implementação lenta',
    winRate: '40%',
  },
]

export const mockContracts: Contract[] = [
  {
    id: '1',
    accountId: '1',
    mrr: 15000,
    startDate: '2022-01-01',
    endDate: '2024-01-01',
    status: 'Ativo',
  },
  {
    id: '2',
    accountId: '4',
    mrr: 2000,
    startDate: '2021-06-01',
    endDate: '2023-11-01',
    status: 'Expirando',
  },
]
