import {
  Account,
  Contact,
  Opportunity,
  OpportunityStakeholder,
  Activity,
  Lead,
  Competitor,
  Contract,
  Proposal,
  AccessProfile,
  AppUser,
} from '@/types'

export const mockAccounts: Account[] = [
  {
    id: '1',
    name: 'Stark Industries',
    logo: 'https://img.usecurling.com/i?q=stark&shape=fill&color=azure',
    segment: 'industria',
    porte: '10001+',
    accountTier: 'ouro',
    status: 'ativa',
    accountHealth: 'saudavel',
    relationshipStatus: 'estabelecido',
    lastInteractionAt: '2023-10-01',
    whiteSpaceNotes: 'Falta oferecer soluções cloud.',
  },
  {
    id: '2',
    name: 'Wayne Enterprises',
    logo: 'https://img.usecurling.com/i?q=wayne&shape=fill&color=black',
    segment: 'servico',
    porte: '10001+',
    accountTier: 'platina',
    status: 'ativa',
    accountHealth: 'saudavel',
    relationshipStatus: 'estabelecido',
    lastInteractionAt: '2023-10-15',
    whiteSpaceNotes: 'Expandir cibersegurança.',
  },
  {
    id: '3',
    name: 'Globex Corp',
    logo: 'https://img.usecurling.com/i?q=globex&shape=fill&color=blue',
    segment: 'industria',
    porte: '201-500',
    accountTier: 'prata',
    status: 'inativa',
    accountHealth: 'dormindo',
    relationshipStatus: 'dormindo',
    lastInteractionAt: '2023-08-10',
    whiteSpaceNotes: '',
  },
  {
    id: '4',
    name: 'Initech',
    logo: 'https://img.usecurling.com/i?q=initech&shape=fill&color=gray',
    segment: 'servico',
    porte: '51-100',
    accountTier: 'bronze',
    status: 'ativa',
    accountHealth: 'em_risco',
    relationshipStatus: 'em_risco',
    lastInteractionAt: '2023-10-20',
    whiteSpaceNotes: 'Cross-sell de licenças.',
  },
]

export const mockContacts: Contact[] = [
  {
    id: '1',
    accountId: '1',
    name: 'Tony Stark',
    position: 'CEO',
    email: 'tony@stark.com',
    phone: '11999999999',
    influenceLevelGlobal: 'alto',
    relationshipStrength: 'forte',
  },
  {
    id: '2',
    accountId: '1',
    name: 'Pepper Potts',
    position: 'COO',
    email: 'pepper@stark.com',
    phone: '11999999998',
    influenceLevelGlobal: 'alto',
    relationshipStrength: 'forte',
  },
  {
    id: '3',
    accountId: '2',
    name: 'Bruce Wayne',
    position: 'CEO',
    email: 'bruce@wayne.com',
    phone: '11999999997',
    influenceLevelGlobal: 'alto',
    relationshipStrength: 'medio',
  },
]

export const mockOpps: Opportunity[] = [
  {
    id: '1',
    accountId: '1',
    title: 'Migração ERP Global',
    opportunityOwnerId: 'user-1',
    value: 2500000,
    currency: 'BRL',
    saleType: 'one_shot',
    modality: 'revenda',
    partner: 'aws',
    stage: 'proposta_enviada',
    temperature: 'quente',
    nextStep: 'Aprovação do Board',
    nextStepDate: '2024-11-05',
    expectedCloseDate: '2024-12-10',
    isOverdue: false,
    identifiedPain: 'Sistemas legados lentos',
    decisionCriteria: 'ROI em 12 meses',
    decisionProcess: 'Aprovação CEO',
    budgetStatus: 'confirmado',
    championStatus: 'confirmado',
    economicBuyerStatus: 'identificado',
    statusFollowUp: 'em_dia',
    createdAt: '2023-01-10T10:00:00.000Z',
    stageUpdatedAt: '2024-02-15T10:00:00.000Z',
  },
  {
    id: '2',
    accountId: '2',
    title: 'Auditoria de Segurança',
    opportunityOwnerId: 'user-1',
    value: 500000,
    currency: 'BRL',
    saleType: 'recorrente',
    modality: 'agenciamento',
    partner: 'fortinet',
    stage: 'qualificacao',
    temperature: 'morna',
    nextStep: 'Demo técnica',
    nextStepDate: '2024-03-25',
    expectedCloseDate: '2024-05-15',
    isOverdue: true,
    identifiedPain: 'Vazamento recente',
    decisionCriteria: '',
    decisionProcess: '',
    budgetStatus: 'nao_confirmado',
    championStatus: 'nao_identificado',
    economicBuyerStatus: 'identificado',
    statusFollowUp: 'atrasado',
    createdAt: '2023-05-20T10:00:00.000Z',
    stageUpdatedAt: '2024-01-10T10:00:00.000Z',
  },
  {
    id: '3',
    accountId: '4',
    title: 'Licenças Office 365',
    opportunityOwnerId: 'user-2',
    value: 120000,
    currency: 'BRL',
    saleType: 'recorrente',
    modality: 'revenda',
    partner: 'outro',
    stage: 'negociacao',
    temperature: 'fria',
    nextStep: 'Assinar contrato',
    nextStepDate: '2024-04-10',
    expectedCloseDate: '2024-04-20',
    isOverdue: false,
    identifiedPain: 'Falta de colaboração',
    decisionCriteria: 'Preço',
    decisionProcess: 'Compras',
    budgetStatus: 'confirmado',
    championStatus: 'identificado',
    economicBuyerStatus: 'nao_identificado',
    statusFollowUp: 'critico',
    createdAt: '2024-02-01T10:00:00.000Z',
    stageUpdatedAt: '2024-03-15T10:00:00.000Z',
  },
]

export const mockStakeholders: OpportunityStakeholder[] = [
  {
    id: 'sh1',
    opportunityId: '1',
    accountId: '1',
    contactId: '1',
    contactName: 'Tony Stark',
    role: 'decision_maker',
    influenceLevel: 'alto',
    seniorityLevel: 'c_level',
    stance: 'favoravel',
    accessLevel: 'total',
    isChampion: true,
    isEconomicBuyer: false,
    isDecisionMaker: true,
    createdAt: '2024-01-10T10:00:00.000Z',
  },
  {
    id: 'sh2',
    opportunityId: '1',
    accountId: '1',
    contactId: '2',
    contactName: 'Pepper Potts',
    role: 'economic_buyer',
    influenceLevel: 'alto',
    seniorityLevel: 'diretor',
    stance: 'neutro',
    accessLevel: 'moderado',
    isChampion: false,
    isEconomicBuyer: true,
    isDecisionMaker: false,
    createdAt: '2024-01-11T10:00:00.000Z',
  },
]

export const mockActivities: Activity[] = [
  {
    id: '1',
    subject: 'Apresentação da proposta',
    accountId: '1',
    accountName: 'Stark Industries',
    opportunityId: '1',
    opportunityTitle: 'Migração ERP Global',
    type: 'meeting',
    channel: 'reuniao_online',
    scheduledDate: '2023-10-20T14:00:00.000Z',
    interactionAt: '2023-10-20T15:00:00.000Z',
    status: 'concluida',
    summary: 'Apresentação comercial e técnica da proposta.',
    details:
      'O cliente gostou da arquitetura proposta, mas questionou o tempo de implantação. Precisamos ajustar o cronograma e apresentar novamente.',
    outcome: 'positivo',
    engagementLevel: 'alto',
    priority: 'alta',
    completed: true,
    completedAt: '2023-10-20T15:00:00.000Z',
    durationMinutes: 60,
    customerSignals: 'Alta urgência para resolver o problema de legado.',
    createdAt: '2023-10-15T10:00:00.000Z',
  },
  {
    id: '2',
    subject: 'Follow-up demo técnica',
    accountId: '2',
    accountName: 'Wayne Enterprises',
    opportunityId: '2',
    opportunityTitle: 'Auditoria de Segurança',
    type: 'call',
    channel: 'telefone',
    scheduledDate: '2023-10-15T10:00:00.000Z',
    status: 'atrasada',
    summary: 'Ligar para saber o feedback da demo.',
    priority: 'media',
    isOverdue: true,
    nextStepDate: '2023-10-16T10:00:00.000Z',
    createdAt: '2023-10-10T10:00:00.000Z',
  },
  {
    id: '3',
    subject: 'Email de reengajamento',
    accountId: '3',
    accountName: 'Globex Corp',
    type: 'email',
    channel: 'email',
    scheduledDate: '2023-08-10T09:00:00.000Z',
    interactionAt: '2023-08-10T09:15:00.000Z',
    status: 'concluida',
    summary: 'Enviado email com novidades do portfólio.',
    outcome: 'neutro',
    engagementLevel: 'baixo',
    priority: 'baixa',
    completed: true,
    createdAt: '2023-08-09T10:00:00.000Z',
  },
]

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Clark Kent',
    company: 'Daily Planet',
    status: 'Novo',
    source: 'Webinar',
    createdAt: '2023-10-22',
  },
  {
    id: '2',
    name: 'Lex Luthor',
    company: 'LexCorp',
    status: 'Qualificado',
    source: 'Indicação',
    createdAt: '2023-10-18',
  },
]

export const mockCompetitors: Competitor[] = [
  {
    id: '1',
    name: 'TechSolutions SA',
    strength: 'Preço agressivo',
    weakness: 'Suporte ruim',
    winRate: '65%',
  },
  {
    id: '2',
    name: 'Global Systems',
    strength: 'Presença global',
    weakness: 'Implementação lenta',
    winRate: '40%',
  },
]

export const mockContracts: Contract[] = [
  {
    id: '1',
    accountId: '1',
    mrr: 15000,
    startDate: '2022-01-01',
    endDate: '2024-01-01',
    status: 'Ativo',
  },
  {
    id: '2',
    accountId: '4',
    mrr: 2000,
    startDate: '2021-06-01',
    endDate: '2023-11-01',
    status: 'Expirando',
  },
]

export const mockProfiles: AccessProfile[] = [
  {
    id: '1',
    name: 'Administrador Global',
    description: 'Acesso total a todos os recursos, configurações e relatórios da plataforma.',
    type: 'sistema',
    status: 'ativo',
    createdAt: '2023-01-10T10:00:00.000Z',
    permissions: {
      dashboard: { visualizar: true },
      leads: { visualizar: true, criar: true, editar: true, excluir: true, escopo: 'tudo' },
      opportunities: { visualizar: true, criar: true, editar: true, excluir: true, escopo: 'tudo' },
      contacts: { visualizar: true, criar: true, editar: true, excluir: true, escopo: 'tudo' },
      accounts: { visualizar: true, criar: true, editar: true, excluir: true, escopo: 'tudo' },
      proposals: { visualizar: true, criar: true, editar: true, excluir: true, escopo: 'tudo' },
      tickets: { visualizar: true, criar: true, editar: true, excluir: true, escopo: 'tudo' },
      campaigns: { visualizar: true, criar: true, editar: true, excluir: true },
      competitors: { visualizar: true, criar: true, editar: true, excluir: true },
      distributors: { visualizar: true, criar: true, editar: true, excluir: true },
      reports: { visualizar: true, exportar: true },
      settings: { visualizar: true, gerenciar_perfis: true, gerenciar_usuarios: true },
      avancadas: {
        visualizar_valores_financeiros: true,
        exportar_dados: true,
        acessar_relatorios_avancados: true,
        gerenciar_tags: true,
        visualizar_auditoria: true,
        atribuir_registros: true,
        excluir_em_massa: true,
        importar_dados: true,
      },
    },
  },
  {
    id: '2',
    name: 'Executivo de Vendas',
    description:
      'Acesso às oportunidades e contas próprias. Sem permissão para exclusão de registros e acessos administrativos.',
    type: 'personalizado',
    status: 'ativo',
    createdAt: '2023-02-15T10:00:00.000Z',
    permissions: {
      dashboard: { visualizar: true },
      leads: { visualizar: true, criar: true, editar: true, excluir: false, escopo: 'proprio' },
      opportunities: {
        visualizar: true,
        criar: true,
        editar: true,
        excluir: false,
        escopo: 'proprio',
      },
      contacts: { visualizar: true, criar: true, editar: true, excluir: false, escopo: 'proprio' },
      accounts: { visualizar: true, criar: true, editar: true, excluir: false, escopo: 'proprio' },
      proposals: { visualizar: true, criar: true, editar: true, excluir: false, escopo: 'proprio' },
      avancadas: {
        visualizar_valores_financeiros: true,
      },
    },
  },
]

export const mockUsers: AppUser[] = [
  {
    id: 'u0',
    name: 'Admin LeapIT',
    email: 'ematunaga@gmail.com',
    role: 'Administrador Global',
    profileId: '1',
    status: 'ativo',
    origin: 'crm',
    syncStatus: 'synced',
    lastSyncAt: '2024-03-10T10:00:00Z',
    createdAt: '2023-01-10T10:00:00.000Z',
  },
  {
    id: 'u1',
    name: 'Ana Silva',
    email: 'ana@leapit.com',
    role: 'Administradora',
    profileId: '1',
    status: 'ativo',
    origin: 'crm',
    syncStatus: 'synced',
    lastSyncAt: '2024-03-10T10:00:00Z',
    createdAt: '2023-01-10T10:00:00.000Z',
  },
  {
    id: 'u2',
    name: 'Carlos Santos',
    email: 'carlos@leapit.com',
    role: 'Vendedor',
    profileId: '2',
    status: 'ativo',
    origin: 'precificacao',
    syncStatus: 'pending',
    createdAt: '2023-03-15T10:00:00.000Z',
  },
  {
    id: 'u3',
    name: 'Mariana Costa',
    email: 'mariana@leapit.com',
    role: 'Gerente Comercial',
    profileId: '1',
    status: 'ativo',
    origin: 'crm',
    syncStatus: 'error',
    createdAt: '2023-05-20T10:00:00.000Z',
  },
  {
    id: 'u4',
    name: 'Pedro Ferreira',
    email: 'pedro@leapit.com',
    role: 'SDR',
    profileId: '2',
    status: 'inativo',
    origin: 'crm',
    syncStatus: 'synced',
    lastSyncAt: '2024-01-05T10:00:00Z',
    createdAt: '2023-08-10T10:00:00.000Z',
  },
]
