import {
  Account,
  Contact,
  Opportunity,
  Activity,
  Lead,
  Competitor,
  Contract,
  Proposal,
} from '@/types'

export const mockAccounts: Account[] = [
  {
    id: '1',
    name: 'Stark Industries',
    logo: 'https://img.usecurling.com/i?q=stark&shape=fill&color=azure',
    segment: 'industria',
    porte: '10001+',
    accountTier: 'ouro',
    status: 'ativa',
    accountHealth: 'saudavel',
    relationshipStatus: 'estabelecido',
    lastInteractionAt: '2023-10-01',
    whiteSpaceNotes: 'Falta oferecer soluções cloud.',
  },
  {
    id: '2',
    name: 'Wayne Enterprises',
    logo: 'https://img.usecurling.com/i?q=wayne&shape=fill&color=black',
    segment: 'servico',
    porte: '10001+',
    accountTier: 'platina',
    status: 'ativa',
    accountHealth: 'saudavel',
    relationshipStatus: 'estabelecido',
    lastInteractionAt: '2023-10-15',
    whiteSpaceNotes: 'Expandir cibersegurança.',
  },
  {
    id: '3',
    name: 'Globex Corp',
    logo: 'https://img.usecurling.com/i?q=globex&shape=fill&color=blue',
    segment: 'industria',
    porte: '201-500',
    accountTier: 'prata',
    status: 'inativa',
    accountHealth: 'dormindo',
    relationshipStatus: 'dormindo',
    lastInteractionAt: '2023-08-10',
    whiteSpaceNotes: '',
  },
  {
    id: '4',
    name: 'Initech',
    logo: 'https://img.usecurling.com/i?q=initech&shape=fill&color=gray',
    segment: 'servico',
    porte: '51-100',
    accountTier: 'bronze',
    status: 'ativa',
    accountHealth: 'em_risco',
    relationshipStatus: 'em_risco',
    lastInteractionAt: '2023-10-20',
    whiteSpaceNotes: 'Cross-sell de licenças.',
  },
]

export const mockContacts: Contact[] = [
  {
    id: '1',
    accountId: '1',
    name: 'Tony Stark',
    position: 'CEO',
    email: 'tony@stark.com',
    phone: '11999999999',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=1',
    influenceLevelGlobal: 'alto',
    relationshipStrength: 'forte',
  },
  {
    id: '2',
    accountId: '1',
    name: 'Pepper Potts',
    position: 'COO',
    email: 'pepper@stark.com',
    phone: '11999999998',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=2',
    influenceLevelGlobal: 'alto',
    relationshipStrength: 'forte',
  },
  {
    id: '3',
    accountId: '2',
    name: 'Bruce Wayne',
    position: 'CEO',
    email: 'bruce@wayne.com',
    phone: '11999999997',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=3',
    influenceLevelGlobal: 'alto',
    relationshipStrength: 'medio',
  },
]

export const mockOpps: Opportunity[] = [
  {
    id: '1',
    accountId: '1',
    title: 'Migração ERP Global',
    opportunityOwnerId: 'user-1',
    value: 2500000,
    currency: 'BRL',
    saleType: 'one_shot',
    modality: 'revenda',
    partner: 'aws',
    stage: 'proposta_enviada',
    temperature: 'quente',
    nextStep: 'Aprovação do Board',
    nextStepDate: '2023-11-05',
    isOverdue: false,
    identifiedPain: 'Sistemas legados lentos',
    decisionCriteria: 'ROI em 12 meses',
    decisionProcess: 'Aprovação CEO',
    budgetStatus: 'confirmado',
    championStatus: 'confirmado',
    economicBuyerStatus: 'identificado',
  },
  {
    id: '2',
    accountId: '2',
    title: 'Auditoria de Segurança',
    opportunityOwnerId: 'user-1',
    value: 500000,
    currency: 'BRL',
    saleType: 'recorrente',
    modality: 'agenciamento',
    partner: 'fortinet',
    stage: 'qualificacao',
    temperature: 'morna',
    nextStep: 'Demo técnica',
    nextStepDate: '2023-10-25',
    isOverdue: true,
    identifiedPain: 'Vazamento recente',
    decisionCriteria: '',
    decisionProcess: '',
    budgetStatus: 'nao_confirmado',
    championStatus: 'nao_identificado',
    economicBuyerStatus: 'identificado',
  },
  {
    id: '3',
    accountId: '4',
    title: 'Licenças Office 365',
    opportunityOwnerId: 'user-2',
    value: 120000,
    currency: 'BRL',
    saleType: 'recorrente',
    modality: 'revenda',
    partner: 'outro',
    stage: 'negociacao',
    temperature: 'fria',
    nextStep: 'Assinar contrato',
    nextStepDate: '2023-11-10',
    isOverdue: false,
    identifiedPain: 'Falta de colaboração',
    decisionCriteria: 'Preço',
    decisionProcess: 'Compras',
    budgetStatus: 'confirmado',
    championStatus: 'identificado',
    economicBuyerStatus: 'nao_identificado',
  },
]

export const mockActivities: Activity[] = [
  {
    id: '1',
    relatedTo: 'Opportunity',
    relatedId: '1',
    type: 'Meeting',
    date: '2023-10-20',
    status: 'Concluída',
    summary: 'Apresentação da proposta',
    outcome: 'Positivo',
  },
  {
    id: '2',
    relatedTo: 'Opportunity',
    relatedId: '2',
    type: 'Call',
    date: '2023-10-15',
    status: 'Pendente',
    summary: 'Follow-up demo técnica',
    isOverdue: true,
  },
  {
    id: '3',
    relatedTo: 'Account',
    relatedId: '3',
    type: 'Email',
    date: '2023-08-10',
    status: 'Concluída',
    summary: 'Email de reengajamento',
    outcome: 'Neutro',
  },
]

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Clark Kent',
    company: 'Daily Planet',
    status: 'Novo',
    source: 'Webinar',
    createdAt: '2023-10-22',
  },
  {
    id: '2',
    name: 'Lex Luthor',
    company: 'LexCorp',
    status: 'Qualificado',
    source: 'Indicação',
    createdAt: '2023-10-18',
  },
]

export const mockCompetitors: Competitor[] = [
  {
    id: '1',
    name: 'TechSolutions SA',
    strength: 'Preço agressivo',
    weakness: 'Suporte ruim',
    winRate: '65%',
  },
  {
    id: '2',
    name: 'Global Systems',
    strength: 'Presença global',
    weakness: 'Implementação lenta',
    winRate: '40%',
  },
]

export const mockContracts: Contract[] = [
  {
    id: '1',
    accountId: '1',
    mrr: 15000,
    startDate: '2022-01-01',
    endDate: '2024-01-01',
    status: 'Ativo',
  },
  {
    id: '2',
    accountId: '4',
    mrr: 2000,
    startDate: '2021-06-01',
    endDate: '2023-11-01',
    status: 'Expirando',
  },
]
